build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bin Collector for Simbio"
  org.opencontainers.image.description: "Bin collection schedule fetcher for Simbio"
  org.opencontainers.image.source: "https://github.com/rozicdejan/ha-bin-simbio-collector"
args:
  GO_VERSION: "1.18"