#ARG BUILD_FROM
#FROM $BUILD_FROM
# Use the official Golang image with Go 1.18 for building the application
FROM golang:1.18-alpine AS builder

# Install necessary dependencies
RUN apk add --no-cache bash jq

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY main.go .
COPY template.html .
COPY static ./static

# Build the Go app
RUN go build -o bin-waste-collection main.go


ENTRYPOINT ["/app/bin-waste-collection"]